### ISSUE TITLE
The HLIP_controller question

### ISSUE THREAD

**Issue by Songchaopipi** [well-robotics/STRIDE#1]
This work is very nice and I have successfully run the code.But I have some questions about the code.
The HLIP stepping controller in HLIP.cpp is:

this->step_real = this->step_size + this->Kdeadbeat.dot((state_real - this->HLIP_final_state))

so the state_real seems like the SSP+ state, which is the start state of a step. But in the HLIP literature， the controller is the 
SSP- state. I tried replacing state_real with the SSP state predicted by LIP dynamics, but it seems to result in an excessively large step size.

Is it my understanding that is incorrect, or is this setup perhaps better suited for the STRIDER robot?

**Comment by Yicheng-Zeng** [comment]
Thank you for your appreciation!

You are right about the statement in literature, pre-imact state( $SSP-$ ) should be used for calculating step size. Since `output-real` passed in output_controller is post impact state when the impact is detected, we used the following code to calculate pre-impact state: 
`xerr<<(COM_state(0) - output_state_real(1)), (COM_state(1)-doutput_state_real(1));`
Here variable `xerr` indicates the pre-impact state and is used for calculating `step_real`.

Please keep me posted if your implementation using LIP dynamics still have diverging step size.
